config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/normflow-plugin:
      branch: mlflow-intertwin-demo
      repo: https://github.com/interTwin-eu/normflow-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/normflow-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-orange-wolf.sh
        container: qc.acc_shabby-xanthic-antelope
  QC.Doc:
    repos:
      github.com/interTwin-eu/normflow-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-olivine-loon.sh
        container: qc.doc_fuzzy-champagne-harrier
      github.com/interTwin-eu/normflow-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-maroon-iguana.sh
        container: qc.doc_seedy-linen-akita
      github.com/interTwin-eu/normflow-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-aqua-discus.sh
        container: qc.doc_goopy-cinnabar-akita
  QC.Lic:
    repos:
      github.com/interTwin-eu/normflow-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-orange-crocodile.sh
        container: qc.lic_cloudy-mauve-hare
  QC.Met:
    repos:
      github.com/interTwin-eu/normflow-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-teal-tarantula.sh
        container: qc.met_homey-orange-catfish
  QC.Sec:
    repos:
      github.com/interTwin-eu/normflow-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-zucchini-olm.sh
        container: qc.sec_randy-charcoal-stingray
  QC.Sty:
    repos:
      github.com/interTwin-eu/normflow-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-flax-cockroach.sh
        container: qc.sty_flabby-russet-squirrel
      github.com/interTwin-eu/normflow-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-olivine-goose.sh
        container: qc.sty_hasty-dandelion-clam
      github.com/interTwin-eu/normflow-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-harlequin-ocelot.sh
        container: qc.sty_lousy-teal-chipmunk
  QC.Uni:
    repos:
      github.com/interTwin-eu/normflow-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-carmine-wildebeest.sh
        container: qc.uni_muggy-denim-tapir
  QC.Ver:
    repos:
      github.com/interTwin-eu/normflow-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-pear-whippet.sh
        container: qc.ver_sleepy-aquamarine-cat
timeout: 5400
