config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/normflow-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/normflow-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/normflow-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-salmon-buzzard.sh
        container: qc.acc_bluesy-corn-ray
  QC.Doc:
    repos:
      github.com/interTwin-eu/normflow-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-brass-devil.sh
        container: qc.doc_pokey-mustard-quoll
      github.com/interTwin-eu/normflow-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-tan-raccoon.sh
        container: qc.doc_sickly-indigo-millipede
      github.com/interTwin-eu/normflow-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-beige-crocodile.sh
        container: qc.doc_slaphappy-firebrick-mouse
  QC.Lic:
    repos:
      github.com/interTwin-eu/normflow-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-carmine-manatee.sh
        container: qc.lic_smelly-cyan-mongrel
  QC.Met:
    repos:
      github.com/interTwin-eu/normflow-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-wheat-quail.sh
        container: qc.met_breezy-amethyst-newt
  QC.Sec:
    repos:
      github.com/interTwin-eu/normflow-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-grey-donkey.sh
        container: qc.sec_shaggy-platinum-grouse
  QC.Sty:
    repos:
      github.com/interTwin-eu/normflow-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-purple-turkey.sh
        container: qc.sty_scaly-pumpkin-lizard
      github.com/interTwin-eu/normflow-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-aquamarine-russel.sh
        container: qc.sty_cranky-pumpkin-budgerigar
      github.com/interTwin-eu/normflow-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-yellow-bonobo.sh
        container: qc.sty_messy-ecru-tuatara
  QC.Uni:
    repos:
      github.com/interTwin-eu/normflow-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-asparagus-markhor.sh
        container: qc.uni_scanty-flax-bison
  QC.Ver:
    repos:
      github.com/interTwin-eu/normflow-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-aquamarine-anteater.sh
        container: qc.ver_skinny-sapphire-butterfly
timeout: 5400
