config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/normflow-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/normflow-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/normflow-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-platinum-mole.sh
        container: qc.acc_leaky-purple-shrimp
  QC.Doc:
    repos:
      github.com/interTwin-eu/normflow-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-peach-buzzard.sh
        container: qc.doc_paltry-puce-neanderthal
      github.com/interTwin-eu/normflow-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-chocolate-mongrel.sh
        container: qc.doc_crappy-malachite-nightingale
      github.com/interTwin-eu/normflow-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-harlequin-squid.sh
        container: qc.doc_tacky-cinnabar-barracuda
  QC.Lic:
    repos:
      github.com/interTwin-eu/normflow-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-cinnamon-jaguar.sh
        container: qc.lic_breezy-amber-hare
  QC.Met:
    repos:
      github.com/interTwin-eu/normflow-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-dandelion-corgi.sh
        container: qc.met_squeaky-goldenrod-molly
  QC.Sec:
    repos:
      github.com/interTwin-eu/normflow-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-bistre-hippopotamus.sh
        container: qc.sec_sickly-celadon-coral
  QC.Sty:
    repos:
      github.com/interTwin-eu/normflow-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-magenta-binturong.sh
        container: qc.sty_woozy-green-booby
      github.com/interTwin-eu/normflow-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-heliotrope-shark.sh
        container: qc.sty_squeaky-aqua-rat
      github.com/interTwin-eu/normflow-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-persimmon-mandrill.sh
        container: qc.sty_randy-mustard-dog
  QC.Uni:
    repos:
      github.com/interTwin-eu/normflow-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.beady-magnolia-owl.sh
        container: qc.uni_baggy-emerald-hippopotamus
  QC.Ver:
    repos:
      github.com/interTwin-eu/normflow-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-olivine-beetle.sh
        container: qc.ver_craggy-lavender-quail
timeout: 5400
