config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/normflow-plugin:
      branch: mlflow-intertwin-demo
      repo: https://github.com/interTwin-eu/normflow-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/normflow-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-red-rattlesnake.sh
        container: qc.acc_foggy-bistre-stoat
  QC.Doc:
    repos:
      github.com/interTwin-eu/normflow-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-teal-clam.sh
        container: qc.doc_lousy-charcoal-kakapo
      github.com/interTwin-eu/normflow-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-corn-javanese.sh
        container: qc.doc_flimsy-goldenrod-dachshund
      github.com/interTwin-eu/normflow-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-sapphire-chinook.sh
        container: qc.doc_snoopy-taupe-reindeer
  QC.Lic:
    repos:
      github.com/interTwin-eu/normflow-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-malachite-termite.sh
        container: qc.lic_cozy-puce-cheetah
  QC.Met:
    repos:
      github.com/interTwin-eu/normflow-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-cream-dachsbracke.sh
        container: qc.met_scanty-magenta-impala
  QC.Sec:
    repos:
      github.com/interTwin-eu/normflow-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-firebrick-mayfly.sh
        container: qc.sec_woolly-gold-dogfish
  QC.Sty:
    repos:
      github.com/interTwin-eu/normflow-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-vermilion-affenpinscher.sh
        container: qc.sty_leaky-yellow-lemming
      github.com/interTwin-eu/normflow-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-lemon-urchin.sh
        container: qc.sty_nippy-crimson-yak
      github.com/interTwin-eu/normflow-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-gold-whale.sh
        container: qc.sty_clammy-violet-yak
  QC.Uni:
    repos:
      github.com/interTwin-eu/normflow-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-rose-rottweiler.sh
        container: qc.uni_surly-red-turkey
  QC.Ver:
    repos:
      github.com/interTwin-eu/normflow-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-corn-reindeer.sh
        container: qc.ver_fuzzy-brass-chow
timeout: 5400
